"""Unit tests for the Lambda scheduler handler (src/carebridge/lambda_scheduler.py)."""

import json
import os
import sys
sys.path.append('src')

from unittest.mock import patch

import boto3
from moto import mock_aws

# Set environment variables
os.environ["STORE"] = "memory"  # use in-memory storage for simplicity in these tests
os.environ["USE_MOCK_BEDROCK"] = "true"
# Ensure no SNS/Email interference
os.environ.pop("SNS_CAREGIVER_TOPIC_ARN", None)
os.environ.pop("USE_SNS", None)
os.environ.pop("USE_EMAIL", None)

from carebridge.lambda_scheduler import lambda_handler as scheduler_handler


def test_lambda_scheduler_medication_checkin():
    """Test that the scheduler creates a medication check-in and starts escalation."""
    with mock_aws():
        event = {
            "user_id": "user1",
            "checkin_type": "medication",
            "metadata": {}
        }
        response = scheduler_handler(event, {})
        assert response["statusCode"] == 200
        body = json.loads(response["body"])
        assert "checkin_id" in body
        assert body["checkin_id"].startswith("checkin_")
        assert "message" in body
        # The message should be generated by llm.py (mock) and contain medicine reference
        assert "medicine" in body["message"].lower()
        # Ensure escalation was started
        from carebridge.escalation import escalation_manager
        state = escalation_manager.get_current_state(body["checkin_id"])
        from carebridge.escalation import EscalationState
        assert state == EscalationState.PENDING


def test_lambda_scheduler_meal_checkin():
    """Test meal check-in."""
    with mock_aws():
        event = {
            "user_id": "user2",
            "checkin_type": "meal",
            "metadata": {}
        }
        response = scheduler_handler(event, {})
        assert response["statusCode"] == 200
        body = json.loads(response["body"])
        assert "checkin_id" in body
        assert "message" in body
        # The message should be generated by llm.py (mock) and for meal type in normal style:
        # "Good morning, {name}! How was your breakfast today?"
        # The name comes from the profile; we are not setting a custom profile, so it uses the default.
        expected_name = "Friend"  # from the default profile in lambda_scheduler.py
        expected_message = f"Good morning, {expected_name}! How was your breakfast today?"
        assert body["message"] == expected_message


def test_lambda_scheduler_mood_checkin():
    """Test mood check-in."""
    with mock_aws():
        event = {
            "user_id": "user3",
            "checkin_type": "mood",
            "metadata": {}
        }
        response = scheduler_handler(event, {})
        assert response["statusCode"] == 200
        body = json.loads(response["body"])
        assert "checkin_id" in body
        assert "message" in body
        assert "feel" in body["message"].lower() or "mood" in body["message"].lower()


def test_lambda_scheduler_general_checkin():
    """Test general check-in (default)."""
    with mock_aws():
        event = {
            "user_id": "user4"
            # no checkin_type, should default to general
        }
        response = scheduler_handler(event, {})
        assert response["statusCode"] == 200
        body = json.loads(response["body"])
        assert "checkin_id" in body
        assert "message" in body
        # The message should be generated by llm.py (mock) and for general type in normal style:
        # "Good morning, {name}! Hope you're having a great day!"
        expected_name = "Friend"  # from the default profile in lambda_scheduler.py
        expected_message = f"Good morning, {expected_name}! Hope you're having a great day!"
        assert body["message"] == expected_message


def test_lambda_scheduler_missing_user_id():
    """Test error when user_id is missing."""
    with mock_aws():
        event = {
            "checkin_type": "medication"
        }
        response = scheduler_handler(event, {})
        assert response["statusCode"] == 400
        body = json.loads(response["body"])
        assert "error" in body
        assert "Missing user_id" in body["error"]